### ISSUE TITLE
Plotting models

### ISSUE THREAD

**Issue by thibautjombart** [mrc-ide/odin#109]
I started working on a plot method for `odin_model` objects. Planned workflow is:

1. create an internal function doing the plotting
2. register it as S3 method
3. later on, use the internal function to define a `$plot` slot in the R6 class and then register the S3 method using this

What we are currently missing is, as far as I can tell, to get explicit flows between the compartments. I would ideally need, assuming `x` is a `odin_model`, something along the lines of (using a SIR model):
```
x$flows() # returns a data.frame
from to rate
"S"  "I"  "beta * S * I / N"
"I"  "R"  "gamma * I"
```
Then making the plot will be trivial. First pass at plot method:
b0fe58675a51bd9ab0540a9281f862392af89ff8

**Comment by richfitz** [comment]
Is this the same as #104 ?

**Comment by richfitz** [comment]
I have moved this work onto the [`i109_model_graph` branch](https://github.com/mrc-ide/odin/tree/i109_model_graph)

**Comment by richfitz** [comment]
continued in #104
