### ISSUE TITLE
User-defined vectors off by one

### ISSUE THREAD

**Issue by ada-w-yan** [mrc-ide/odin#136]
I have the following code in a file `minimal_example.R`:
```
# vector_length
n_I <- 3

# initial conditions
initial(I[1:n_I]) <- I_0[i]

# equations
deriv(I[1:n_I]) <- 0

dim(I) <- n_I
dim(I_0) <- n_I

# initial values
I_0[1:n_I] <- i
```

and I run

```
filename <- "minimal_example.R"
gen <- odin::odin(filename, verbose=FALSE) 
pars <- list()
mod <- gen()
mod$init
```

As an R user, I expect `I_0` to be initialised to `1 2 3`, but because C uses zero indexing, I get `0 1 2`.  Which is fine, I can add 1 to my vector, but I find the behaviour unexpected.

**Comment by richfitz** [comment]
Urgh that's horrible.  I have a new idea about dealing with indexes (#115) which will make this sort of thing more understandable, but of cause break anything that ends up depending on this behaviour

**Comment by richfitz** [comment]
same as #52

**Comment by richfitz** [comment]
Looks like #139 will fix this

**Comment by richfitz** [comment]
From version `0.2.0` onward the new behaviour will be:

* indexes on the rhs have R (base-1) behaviour
* If indexes are used like this (outside of an index expression) then a message will be printed advertising the behaviour change
* this message can be suppressed by using the argument `no_check_naked_index = TRUE` or setting the option `options(odin.no_check_naked_index = TRUE)`
