### ISSUE TITLE
Package symbol registration conflicts with Rcpp's attributes

### ISSUE THREAD

**Issue by richfitz** [mrc-ide/odin#153]

**Comment by BlackEdder** [comment]
I've now run into this. Is there a workaround?

**Comment by richfitz** [comment]
I need a minimal example to do much, but can take a look later in the year if I have one

**Comment by BlackEdder** [comment]
Based on my limited understanding of the intricacies of the c apis and R.

I think the main issue is that rcpp is configured to not export functions (to make them available to the outside) unless they are marked specifically to do so, while odin expects all c functions to be exported automatically.

**Comment by richfitz** [comment]
Fixed by https://github.com/mrc-ide/odin/pull/207
