### ISSUE TITLE
Changing model parameters for use with FME

### ISSUE THREAD

**Issue by paulbuckleyox** [mrc-ide/odin#157]
Hi,
 
I have coded up a model in ‘odin’ today, with the idea of using the model with FME’s modFit function, to perform some minimisation with respect to some observable data. 
 
I’m sure your aware, that these means modFit needs to be able to alter the parameters of the model on the fly, like with deSolve models, and I was wondering if that is possible, with an odin model? 

cheers

**Comment by richfitz** [comment]
Please see the [section of the manual](https://mrc-ide.github.io/odin/articles/odin.html#specifying-parameters) on specifying parameters.  Once your model has parameters specified you can use `$set_user` to set a subset of the parameters.  You will likely have to put that into a helper function for use with an optimiser, something like:

```r
wrapper <- function(model) {
  function(p) {
    model$set_user(a = p[[1]], b = p[[2]])
    model$run(...)
  }
}
```

**Comment by richfitz** [comment]
Ah, I see that FME is a deSolve-based package (I have never used it before). If the above is not sufficiently flexible could you post a basic toy example in R (or your model if you want and if it is relatively simple) and I can look further.  From the look of page 6 of the first vignette though the `ode` call is pretty deep in their wrapper functions, which should be fairly similar to the above

**Comment by paulbuckleyox** [comment]
Perfect, thanks so much for the quick response, i have now got it working. When using deSolve before, it was taking me at least 35 mins to run the modFit algorithm in FME, and now it completes in less than 2 minutes. I had not found the manual, so thanks for your help & for making this package. The $set_user command answered all my problems. Essentially during an FME minimisation routine, you obviously first define the odin model as described in manual. Subsequently you define a parChange function as below that changes the parameters, and in your FME objective function (that returns modCost, and is called by modFit), you can pass the perturbed parameters to the parChange function, and run the model as normal. 

```
parsChange_c = function(p,modelChange){
  modelChange$set_user(a=p[1],b=p[2])
}
```

Then your objective function becomes something along the lines of;

```
Objective = function(x, parset = names(x)) {
  pars[parset] = x
  parsChange_c(pars,mod)
  out = mod$run(t)
  out=as.data.frame(out)
  return(modCost(model = out, obs = allDataPooled,y="value", weight = "std",x="t"))
}
```

where 'x' passed to the function is the parameters, as normal with FME.

**Comment by richfitz** [comment]
Thanks for letting me know - glad it's working for you :raised_hands:
