### ISSUE TITLE
Time variable input into odin

### ISSUE THREAD

**Issue by cuttin** [mrc-ide/odin#158]
Is there a possibility to parse a time variable input data into the code of odin? In other words, how can you reproduce the code below in odin:

```r
require(deSolve)
q <- rnorm(10,50,5) 
params <- list(q = q)
sinit = c(1,2)
times <- 1:length(q)
func <- function(t, y, params) {
  
  with(as.list(c(params, y)), {
    
    qt = q[t]
     
    dc1 = qt*y[1]/55 - 0.5
    dc2 = qt*y[1] + y[2]
    
    res <- c(dc1,dc2)
    list(res)
  })
}
# Run the integration:
out <- ode(sinit, times, func, params, method="ode45")
```

**Comment by richfitz** [comment]
Several ways, depending on what you exactly want to model:

* you can use `t` anywhere in the model, though you cannot index arrays with it
* probably what you want, you can use [interpolating functions](https://mrc-ide.github.io/odin/articles/odin.html#interpolating-functions) to represent a data-driven function of time

See if the example on the vignette helps, and let me know how you get on

**Comment by richfitz** [comment]
Any update on this @cuttin?

**Comment by cuttin** [comment]
As you recommended:

require(odin)
model <- odin::odin({
  deriv(c1) = qt*c1/55 - 0.5
  deriv(c2) = qt*c1 + c2
  initial(c1) <- c01
  initial(c2) <- c02
  qt <- interpolate(times,q,"linear")
  c01 <- user()
  c02 <- user()
  q[] <- user()
  times[] <- user()
  dim(q) <- user()
  dim(times) <- user()
})

mod_od <- model(times=times,q=q,c01=sinit[1],c02=sinit[2])
y <- mod_od$run(times)
plot(y[,2],out[,2])
plot(y[,3],out[,3])
