### ISSUE TITLE
DDE - too large lag value

### ISSUE THREAD

**Issue by paulbuckleyox** [mrc-ide/odin#164]
Hi Rich,

I am having an issue using ODIN for a delay-differential. I am trying to code a complex system of equations, where there is a time delay in one of the derivatives. When I solve the model using odin, i am told that from lsoda, therer is an 'illegal input in lag value y, too large at b.'

I cannot post this model although i have replicated this using a toy model, as per below. I will define the model, post the entire error message, and define the deSolve function that allows me to resolve it. In essence, i am wondering how to resolve this in ODIN.

Odin toy model:
```
library(odin)

model = odin::odin({
  ylag = delay(TcellAct,del)
  initial(TcellAct) = 1
  
  deriv(TcellAct) = r * ylag
  del=user(40)
  r=user(0.1)
  output(ylag)=ylag
  config(base)="model"
  
})

dde= model()

t = seq(0,167.5,by=0.1)

out = dde$run(t)


```

The error message i receive is 'Error in lsoda(y, times, func, parms, lags = control, ...) : 
  illegal input in lagvalue - lag, 0.00332459, too large, at time = 40'

So, if i write this as a desolve function for dede, i am able to resolve this using an if statement to avoid the lagvalue being before the simulation beginning. This function is below;

```library(deSolve)
lagFunction = function(t,y,parms,delay){
  r=0.1
  tlag = t - delay
  if(tlag<=0){
    ylag=0.5
  }else {
    ylag = lagvalue(tlag)
  }
  dTcellAct = r*ylag
  list(dTcellAct)
}

pars = c(r=0.5)
yinit= 1
times = seq(0,167.5,by=0.1)
out = dede(y=yinit,times=times,func=lagFunction,parms=NULL,delay=40)
```

This works as expected, even with large delays.

I am wondering how best to implement this in ODIN?

Appreciate your thoughts
Cheers, Paul

**Comment by richfitz** [comment]
Great question and thanks for the easily reproducible example.

The difference between the R code and your odin code seems to be the `mxhist` tuning parameter for `dede`:

```
> out = dde$run(t, n_history = 1000)
Error in lsoda(y, times, func, parms, lags = control, ...) : 
  illegal input in lagvalue - lag, 0.00332459, too large, at time = 40
> out = dde$run(t, n_history = 10000)
```

I should probably increase that to reduce surprises. 

However, 10000 steps seems excessive (looks like `dede` has taken ~6k steps with ~1000 rejected).   If you have installed `dde` you can do

```
mod = model(use_dde=TRUE)
mod$run(t)
```

which solves your system in 19 steps (with 16 rejected).

```r
mod1 <- model(use_dde = FALSE)
mod2 <- model(use_dde = TRUE)
t <- seq(0, 167.5, by = 0.1)

out1 <- mod1$run(t, n_history = 10000)
out2 <- mod2$run(t)
all.equal(unclass(out1), out2, check.attributes = FALSE)
## [1] "Mean relative difference: 9.868525e-06"

microbenchmark::microbenchmark(
  mod1$run(t, n_history = 10000),
  mod2$run(t))
## Unit: microseconds
##                            expr      min        lq      mean   median        uq
##  mod1$run(t, n_history = 10000) 2272.901 2280.7885 2320.3043 2287.604 2306.7365
##                     mod2$run(t)  532.257  542.1365  553.0263  549.624  555.8525
##       max neval
##  4093.688   100
##   697.323   100
```

**Comment by richfitz** [comment]
(sorry just realised those timings are with `-O0` on odin's models and also both packages so are probably off quite badly - but I'd expect the relative difference to remain about the same)

**Comment by paulbuckleyox** [comment]
Hi, 

thanks so much for the quick replies. That has resolved the issue with the toy model. However for my larger model, using the `n_history = (x>=10000)`, i get the same error. If i use `dde` i get the error 'integration failure, step size vanished'.

I am a little confused but have a few things i will try and keep you updated. If you have any insight that could be useful it'd be appreciated! I'm going to try coding up my larger model in the context of a deSolve model with the if statement, as i did in 'lagFunction'

Paul

**Comment by richfitz** [comment]
the `integration failure, step size vanished` error means that in order to reach the required precision, the step size vanished to zero - this unfortunately means that dde can't solve that model.  I suspect the deSolve error is getting at the same thing though because as the step size gets driven down the number of history steps required to span your history grows

**Comment by paulbuckleyox** [comment]
thanks for your reply Rich, that was very useful. The ins and outs of solvers aren't something i'm an expert in. 

So, i have now coded up the larger model as a deSolve function, including the below code, inside the `derivs` function:

`tlag = t - 12
if(tlag<=0){
      ylag=0.5
    }else {
      ylag = lagvalue(tlag)
    }`

Initially, I was receiving integration problems, with the routine finishing early, and errors pointing at singularity issues. After analysing some of the results, I realised some of the results were in the e-11, and e+11 range. Due to this, I changed some of the growth parameters by orders of magnitude, and now the deSolve model solves, trends are reasonable and i'm presented with no error messages or warnings. 

This made me think then the issue with my ODIN model (and using dde), was the parameters, so I've reran the ODIN model with the updated parameters, (using dde, and using n_history=10000), and the results are below. This is using the same equations and parameters as above. As far as i can tell (i've thoroughly checked for coding bugs), the differences known to me, are the tlag code as above, and that it is defined directly in deSolve. 

DDE: same step size vanished issue
n_history=10000 : I get a (very different solution to when using the deSolve function), which ends at t=13.4, (my delay is 12). Past this everything is NaN. I get the following warning: `DLSODA-  Warning..Internal T (=R1) and H (=R2) are
      such that in the machine, T + H = T on the next step  
     (H = step size). Solver will continue anyway.`

Unfortunately i can't send the model equations over, but i can sends $contents, etc. Any thoughts would be greatly appreciated, as ODIN massively reduces run time wrt deSolve.. appreciate it's difficult without me sending the model. 

cheers

P

**Comment by richfitz** [comment]
This is difficult without being able to see the code, yes, but it sounds like you have built different models.

Does the model with odin work if you use `deSolve`?

Things you might try:

* If you grab the most recent version of odin (0.2.1, as of this morning) you will be able to compute derivatives for your model - I would suggest using that at the starting points, before the delays kick in, to verify the non-delay parts of your model.
* If you build the model with: `odin::odin(..., target = "r")` it will generate R code.  With that you can inspect the generated R with a little work by running `environment(mod$initialize)$private$core$rhs_desolve`, for example:

```r
model <- odin::odin({
  ylag <- delay(TcellAct,del)
  initial(TcellAct) <- 1
  deriv(TcellAct) <- r * ylag
  del <- user(40)
  r <- user(0.1)
  output(ylag) <- ylag
}, target = "r")
mod <- model()
environment(mod$initialize)$private$core$rhs_deSolve
```

returns

```r
function (t, state, internal) 
{
    dstatedt <- numeric(length(state))
    output <- numeric(1)
    ylag <- local({
        t <- t - internal[["del"]]
        if (t <= internal[["initial_t"]]) {
            TcellAct <- internal[["initial_TcellAct"]]
        }
        else {
            if (internal[["odin_use_dde"]]) {
                internal[["delay_state_ylag"]] <- dde::ylag(t, 
                  internal[["delay_index_ylag"]])
            }
            else {
                internal[["delay_state_ylag"]] <- deSolve::lagvalue(t, 
                  internal[["delay_index_ylag"]])
            }
            TcellAct <- internal[["delay_state_ylag"]][[1L]]
        }
        TcellAct
    })
    dstatedt[[1L]] <- internal[["r"]] * ylag
    output[[1]] <- ylag
    list(dstatedt, output)
}
```

which will hopefully make clear where the difference in the generated code might be

* Your code `tlag = t; - 12 if(tlag<=0){ ylag=0.5 }else { ylag = lagvalue(tlag) }` (I believe I have found the dropped newline) would be done in odin as `ylag <- delay(y, 12, 0.5)` - note the 3rd argument.  If `y` starts off as 0.5 it should be equivalent to `ylag <- delay(y, 12)`

**Comment by paulbuckleyox** [comment]
Hey. Again, thanks for the reply. I've had a fiddle with this and i've not fixed it, and I still can't figure it out.

I had a look through the rhs_desolve code, and it all seems perfectly accurate. I did notice, that when the command `deSolve::lagvalue(t, 
                  internal[["delay_index_ylag"]])` is called for the generated R code, my deSolve code doesn't pass nr into lagvalue. If i do, i get the lagvalue error, saying `Error in lagvalue(t, 12) : 
  illegal input in lagvalue - var nr too high, 12` .. If i remove the nr argument (i.e 12), it runs and solves fine. I'm struggling to tell whether it's something i'm doing, which i imagine is likely, or I am not using an ODIN setting correctly. 

I have redacted and uploaded part of the model below, which is causing the issue. They're the same equations, using the same parameters as eachother. The model that solves provides some pretty odd results as there's lots of dummy parameters in both of them, so that I could upload only part of the model. The code below for the ODIN model does not use `dde` or set `n_history`, but the issues  remain with those settings. There are some peculiarities with the parameter values etc which do need addressing, but what is perplexing me is that the deSolve model (PC_DDES_DESOLVE) solves :S. Again would appreciate any thoughts.    

Desolve model:

```
library(deSolve)
stateCut = c(cellA=1,cellB=1,cellC=1,cellD=1,cellE=1,cellF=1)
pars = c(
  Vmax_cellA_otherCellType=0.01,
  KMcellA_otherCellType=5,
  OX40Inhibition=0.05,
  otherFactorscellA=0.01,
  Vmax_cellB_otherCellType=1.00,
  KMcellB_otherCellType=0.01,
  cellBInhibition=0.01,
  otherFactorscellB=0.1,
  homeostatic_rec=10.8384,
  VmaxcellC_Rec_Inflammation=0.001,
  KM_CD40Rec=20.0,
  recirculation=10.8,
  Vmax_otherCellType_Ag=0.00000000004,
  KM_otherCellType_Ag=12.0,
  Vmax_otherCellType_ProteinEnhance=0.000001,
  KM_otherCellType_Protein_Enhance=10.0,
  VmaxPrimecellB=0.01,
  KM_PrimecellB=2.0,
  VmaxPrimecellA=1.0,
  KM_PrimecellA=2.0,
  anergy=0.1 ,
  proliferationRate=0.2,
  proliferationMax=2,
  exitOrgan=0.02,
  otherCellType_Ag=40
)
PC_DDES_DESOLVE = function(pars, times=seq(0,167.5,by=0.1), stateCut) {


  derivs = function(t,stateCut,pars){
    tlag = t - 12
    if(tlag<=0){
      ylag=1
    }else {
      ylag = lagvalue(tlag)
    }
    with(as.list(c(stateCut,pars)), {
      dcellA = (Vmax_cellA_otherCellType * 140 *(140/(140+KMcellA_otherCellType))) - OX40Inhibition + otherFactorscellA
      dcellB = (Vmax_cellB_otherCellType * 140 *(140/(140+KMcellB_otherCellType))) - cellBInhibition + otherFactorscellB
      dcellC = homeostatic_rec + (VmaxcellC_Rec_Inflammation * cellC * (140+140/(140+140+KM_CD40Rec))) - (recirculation) - (Vmax_otherCellType_Ag * cellC * 140 * (otherCellType_Ag/(otherCellType_Ag+KM_otherCellType_Ag)) * (Vmax_otherCellType_ProteinEnhance * cellC * 140 * (140/(140+KM_otherCellType_Protein_Enhance))))
      dcellD = + (Vmax_otherCellType_Ag * cellC * 140 * (otherCellType_Ag/(otherCellType_Ag+KM_otherCellType_Ag)) * (Vmax_otherCellType_ProteinEnhance * cellC * 140 * (140/(140+KM_otherCellType_Protein_Enhance)))) - (VmaxPrimecellB * ylag * 140 * (cellB/(cellB+KM_PrimecellB))) - (VmaxPrimecellA * ylag * 140 * (cellA/(cellA+KM_PrimecellA))) - (anergy * ylag)
      dcellE = +(VmaxPrimecellB * ylag * 140 * (cellB/(cellB+KM_PrimecellB))) + (VmaxPrimecellA * ylag * 140 * (cellA/(cellA+KM_PrimecellA))) + (proliferationRate* cellE * (1-cellE/proliferationMax)) - (exitOrgan   * cellE)
      dcellF= +((VmaxPrimecellB * ylag * 140 * (cellB/(cellB+KM_PrimecellB))) + (VmaxPrimecellA * ylag * 140 * (cellA/(cellA+KM_PrimecellA))) + (proliferationRate* cellE * (1-cellE/proliferationMax)) - (exitOrgan   * cellE))  + ((Vmax_otherCellType_Ag * cellC * 140 * (otherCellType_Ag/(otherCellType_Ag+KM_otherCellType_Ag)) * (Vmax_otherCellType_ProteinEnhance * cellC * 140 * (140/(140+KM_otherCellType_Protein_Enhance)))) - (VmaxPrimecellB * ylag * 140 * (cellB/(cellB+KM_PrimecellB))) - (VmaxPrimecellA * ylag * 140 * (cellA/(cellA+KM_PrimecellA))) - (anergy * ylag)) + (homeostatic_rec + (VmaxcellC_Rec_Inflammation * cellC * (140+140/(140+140+KM_CD40Rec))) - (recirculation) - (Vmax_otherCellType_Ag * cellC * 140 * (otherCellType_Ag/(otherCellType_Ag+KM_otherCellType_Ag)) * (Vmax_otherCellType_ProteinEnhance * cellC * 140 * (140/(140+KM_otherCellType_Protein_Enhance)))))
      return(list(c(dcellA,dcellB,dcellC,dcellD,dcellE,dcellF)))
    })
  }
  return(dede(y=stateCut,times=times,func = derivs, parms=pars))
}
out=PC_DDES_DESOLVE(pars,stateCut = stateCut)
outDF = as.data.frame(out)
```

The above model solves fine on my machine. 

ODIN Model.


```
library(odin)
Model2_ODE = odin::odin({
  ylag = delay(cellD,primingDelay)
 
  
  deriv(cellA) = (Vmax_cellA_otherCellType * 140 *(140/(140+KMcellA_otherCellType))) - OX40Inhibition + otherFactorscellA
  deriv(cellB) = (Vmax_cellB_otherCellType * 140 *(140/(140+KMcellB_otherCellType))) - cellBInhibition + otherFactorscellB
  deriv(cellC) = homeostatic_rec + (VmaxcellC_Rec_Inflammation * cellC * (140+140/(140+140+KM_CD40Rec))) - (recirculation) - (Vmax_otherCellType_Ag * cellC * 140 * (otherCellType_Ag/(otherCellType_Ag+KM_otherCellType_Ag)) * (Vmax_otherCellType_ProteinEnhance * cellC * 140 * (140/(140+KM_otherCellType_Protein_Enhance))))
  deriv(cellD) = + (Vmax_otherCellType_Ag * cellC * 140 * (otherCellType_Ag/(otherCellType_Ag+KM_otherCellType_Ag)) * (Vmax_otherCellType_ProteinEnhance * cellC * 140 * (140/(140+KM_otherCellType_Protein_Enhance)))) - (VmaxPrimecellB * ylag * 140 * (cellB/(cellB+KM_PrimecellB))) - (VmaxPrimecellA * ylag * 140 * (cellA/(cellA+KM_PrimecellA))) - (anergy * ylag)
  deriv(cellE) = +(VmaxPrimecellB * ylag * 140 * (cellB/(cellB+KM_PrimecellB))) + (VmaxPrimecellA * ylag * 140 * (cellA/(cellA+KM_PrimecellA))) + (proliferationRate* cellE * (1-cellE/proliferationMax)) - (exitOrgan   * cellE)
  deriv(cellF)= +((VmaxPrimecellB * ylag * 140 * (cellB/(cellB+KM_PrimecellB))) + (VmaxPrimecellA * ylag * 140 * (cellA/(cellA+KM_PrimecellA))) + (proliferationRate* cellE * (1-cellE/proliferationMax)) - (exitOrgan   * cellE))  + ((Vmax_otherCellType_Ag * cellC * 140 * (otherCellType_Ag/(otherCellType_Ag+KM_otherCellType_Ag)) * (Vmax_otherCellType_ProteinEnhance * cellC * 140 * (140/(140+KM_otherCellType_Protein_Enhance)))) - (VmaxPrimecellB * ylag * 140 * (cellB/(cellB+KM_PrimecellB))) - (VmaxPrimecellA * ylag * 140 * (cellA/(cellA+KM_PrimecellA))) - (anergy * ylag)) + (homeostatic_rec + (VmaxcellC_Rec_Inflammation * cellC * (140+140/(140+140+KM_CD40Rec))) - (recirculation) - (Vmax_otherCellType_Ag * cellC * 140 * (otherCellType_Ag/(otherCellType_Ag+KM_otherCellType_Ag)) * (Vmax_otherCellType_ProteinEnhance * cellC * 140 * (140/(140+KM_otherCellType_Protein_Enhance)))))
  
  

  initial(cellA) = 1
  initial(cellB) = 1
  initial(cellC) = 1
  initial(cellD) = 1
  initial(cellE) = 1
  initial(cellF) = 1 #change this
  

  Vmax_cellA_otherCellType=user(0.01)
  KMcellA_otherCellType=user(5)
  OX40Inhibition=user(0.05)
  otherFactorscellA=user(0.01)
  Vmax_cellB_otherCellType=user(1.00)
  KMcellB_otherCellType=user(0.01)
  cellBInhibition=user(0.01)
  otherFactorscellB=user(0.1)
  homeostatic_rec=user(10.8384)
  VmaxcellC_Rec_Inflammation=user(0.001)
  KM_CD40Rec=user(20.0)
  recirculation=user(10.8)
  Vmax_otherCellType_Ag=user(0.00000000004)
  KM_otherCellType_Ag=user(12.0)
  Vmax_otherCellType_ProteinEnhance=user(0.000001)
  KM_otherCellType_Protein_Enhance=user(10.0)
  VmaxPrimecellB=user(0.01)
  KM_PrimecellB=user(2.0)
  VmaxPrimecellA=user(1.0)
  KM_PrimecellA=user(2.0)
  anergy=user(0.1 )
  proliferationRate=user(0.2)
  proliferationMax=user(2)
  exitOrgan=user(0.02)
  otherCellType_Ag=user(40)
  primingDelay=user(12)
  config(base)="Model2_Paracortex_ODE"
}, target="r")
mod = Model2_ODE()
t =seq(0,167.5,by=0.1)

mod$contents()
initialOut = mod$run(t)
initialOut = as.data.frame(initialOut)
plot(initialOut$t,initialOut$cellD)

```

**Comment by richfitz** [comment]
These models look really different - in the deSolve one you are lagging the whole state vector and using it like `VmaxPrimecellB * ylag * 140 * (cellB/(cellB+KM_PrimecellB))` - this is in turn creating a state vector that is much larger than the parameters you are passing in (I see 6 variables going in and 21 derivatives coming out).

In the odin model you are lagging only `cellD`

**Comment by paulbuckleyox** [comment]
Ah, I hadn't noticed that lagvalue returns a vector. Now that i've changed that in the simplified model I uploaded, I'm getting errors. Strangely, when this is changed in the full deSolve model, it still solves. Further, if I remove terms of the cellD equation, the ODIN mdoel solves fine. This makes me think that there is a rate of change issue with either the parameters or the mdoel structure. I'm starting to get somewhere though. I think this can be closed now as not an issue w ODIN, cheers for your help

**Comment by richfitz** [comment]
ok, good luck 😃
