### ISSUE TITLE
better error message when using wrong indexes

### ISSUE THREAD

**Issue by annecori** [mrc-ide/odin#166]
https://github.com/mrc-ide/patchmodel/tree/dccb6740e75bba58bfe8c68efacd43f78d4c80ba

In R/stochastic_seir_patch_odin.R, line 16, if you uncomment the end - error not very helpful

**Comment by richfitz** [comment]
With the change above, this is the behaviour:

```
> odin::odin({
+   m[,] <- user()
+   r[] <- m[i, 1] + m[1, j]
+   dim(m) <- user()
+   dim(r) <- 5
+   initial(x) <- 1
+   update(x) <- 1
+ })
Error: Index variable 'j' not possible for array of rank 1
	r[] <- m[i, 1] + m[1, j] # (line 2)
```
