### ISSUE TITLE
workdir arg for odin options not working when passing to odin_build or odin

### ISSUE THREAD

**Issue by r-ash** [mrc-ide/odin#167]
To recreate

```
gen <- odin({
  ylag <- delay(y, 3, 2)
  initial(y) <- 0.5
  deriv(y) <- 0.2 * ylag * 1 / (1 + ylag^10) - 0.1 * y
  output(ylag) <- ylag
  config(base) <- "delay3"
}, workdir = ".")
```

Expect this to compile code to "c" file in current working directory but not the case. File is still created in the tempdir.

Similarly using `odin_build` on the IR with `options = odin_options(workdir = ".")` doesn't create compiled file in the working directory.

**Comment by richfitz** [comment]
As discussed on slack, this was caused by not skipping the cache.  There's a test for the caching and workdir behaviour here: https://github.com/mrc-ide/odin/blob/5128a5737f5611c6577ae0cef9bf72f033e0e78f/tests/testthat/test-ring-cache.R#L51-L64
