### ISSUE TITLE
Incompatible types and integers without casts

### ISSUE THREAD

**Issue by arranhamlet** [mrc-ide/odin#169]
When compiling my model ```https://github.com/arranhamlet/yf_monkey_model/yf_monkey_model.R```, by running ```mass_run_NHP.R``` I get numerous errors using the latest verison of odin, but none when using the previous install I had of "mrc-ide/odin@ebbb60377a025e7bcd95f82ffb6077921084dae3".

For example
``` odin_33833b2d.c:1123:27: error: incompatible types when assigning to type 'double *' from type 'double' internal->bite_per_time = 0.20000000000000001;```

``` odin_33833b2d.c:1131:36: warning: assignment makes pointer from integer without a cast internal->maximum_bites_per_host = 20;```

```make: *** [C:/PROGRA~1/R/R-35~1.1/etc/x64/Makeconf:208: odin_33833b2d.o] Error 1```

**Comment by richfitz** [comment]
can we close this now @arranhamlet ?

**Comment by arranhamlet** [comment]
Yes
