### ISSUE TITLE
odin_prepare

### ISSUE THREAD

**Issue by eloycyst** [mrc-ide/odin#180]
Hello,
I am using a package (EPICYST) that also use odin, but when I try to use EPICYST, it fails because there is not a function called odin_prepare. I contacted with the developers of the EPICYST package and they told me that this is an error of odin. I want to know if you know something about this error.
thanks.
install.packages("devtools")
install.packages("usethis")
library(usethis)
library(devtools)
find_rtools()
devtools::install_github("mrc-ide/odin", upgrade = FALSE) 
#or
install.packages("odin")
library(odin)
devtools::install_github("pwinskill/EPICYST")
#or
install.packages("EPICYST")
library(EPICYST)
####
Initialise<-Set_up()
# View parameters
Initialise[[1]][1:5]
# View state variable starting values
Initialise[[2]][6:7]
M1<-Run_model(Time=50)
M2<-Run_model(Time=50, Burn_in=25)
??odin_prepare
####
odin::can_compile()
can_compile(EPICYST)
###
odin::odin_package(".")

**Comment by richfitz** [comment]
Hi there - either use an old version of `odin`, or get @pwinskill to update that package to work with the current version of `odin` (Pete - you just need to regenerate the package code I think)
