### ISSUE TITLE
feature question: root detection and start/stop integration

### ISSUE THREAD

**Issue by slwu89** [mrc-ide/odin#204]
Hi!

I have a question about how difficult the following features would be to implement, if it seems reasonable and possible, I'd appreciate being pointed to the parts of the code to do so.

1. I'm curious if odin supports root detection (https://rdrr.io/cran/deSolve/man/events.html) or could be extended to do so.
2. (More fanciful) I'm curious if it is even plausible to incorporate an interface similar to the integrator interface of DifferentialEquations.jl (https://diffeq.sciml.ai/stable/basics/integrator/) which allows a user to create a model, integrate to some point, stop integration, and restart from that point. I'm especially curious if that would be possible for DDEs, which would require preserving whatever data structure stores the previous values, between starts/stops of the integrator.

Thanks!

**Comment by slwu89** [comment]
I just found https://mrc-ide.github.io/dde/index.html and realized all of those features are implemented in your other great packages....will read more next time. Thanks!

**Comment by richfitz** [comment]
Hi @slwu89 (cleaning through issues - I tend to miss these sorry)

Proper event support in odin has been on the backlog for *ages*. It's hard to get right though, and so has never made it into the package despite a few goes at it.

Starting and stopping integration should work fine - we do this a lot internally. Be aware that with the pointer passed back from dde it will not survive serialisation.

You may also be interested in dust/odin.dust (though delays are not supported there at all)

**Comment by slwu89** [comment]
Thanks for the insight @richfitz. I've looked at dust, and seems very interesting. My specific use case is that I am working on a particular type of stochastic sampling algorithm, part of which involves solving a DDE subject to some root function, upon which the integration must terminate, a parameter is changed, and integration continues, so I was interested in odin/dde because it seemed to be the only dde solver in R that allowed one to make an object and then integrate along intervals. I'll be sure to keep on the lookout for event support!
