### ISSUE TITLE
output for intermediate data and cyclic dependancy solving

### ISSUE THREAD

**Issue by xtimbeau** [mrc-ide/odin#228]
Thanks again for this great package. I have a lot of fun using it and it delivers quite smoothly.
It would be great to be able to output variable that are defined in the model directly. update variable are output automatically but when i write ;

```
library(odin)
#1 this works
a_model <- odin({
  update(x) <- x + y
  y <- x
  initial(x) <- 1
  output(y) <- y
})
a_model$new()$run(5)
#2 this also with dimensions, and output of y_o
a_model <- odin({
  update(x[]) <- x[i] + y[i]
  y[] <- x[i]
  initial(x[]) <- 1
  dim(x) <- 5
  dim(y) <- 5
  output(y_o[]) <- y[i]
  dim(y_o) <- 5
})
a_model$new()$run(5)
#3 this doesn't compile and returns this error
# Error in mapply(FUN = f, ..., SIMPLIFY = FALSE) : 
# zero-length inputs cannot be mixed with those of non-zero length
a_model <- odin({
  update(x[]) <- x[i] + y[i]
  y[] <- x[i]
  initial(x[]) <- 1
  dim(x) <- 5
  dim(y) <- 5
  output(y[]) <- y[i]
})
```
Would it not be more consistent to have #3 function as #1 ?

My second request would be a possibility tyo deal with cyclic dependancy with a solver, one way or the other, possibly a callback. It would be nice to be able to do the solving quickly in C.

**Comment by richfitz** [comment]
I've fixed the error here: https://github.com/mrc-ide/odin/pull/229 (the incomprehensible eventual mapply error is concerning, and I can see how this would happen). This will get merged in the next day or so, ahead of the update to CRAN we're sorting out.

It's not documented anywhere, but `output` with discrete time models is going to be discouraged. We're in the process of moving most of the discrete time work into a new package "dust" (via odin.dust) which is much faster and parallelisable (see https://mrc-ide.github.io/dust/articles/design.html), however, we dropped update support for this. It's something that is needed for continuous time models. I doubt we'll ever retire it directly but we will start encouraging dust use once that's on CRAN.

For your second request, could you open a new issue, ideally with a minimal example and some indication of timings? The current topological sort is very simple but it's not been an insurmountable problem for us with some very large models (see [here](https://github.com/mrc-ide/sircovid/blob/master/inst/odin/carehomes.R) for example)

**Comment by xtimbeau** [comment]
Thanks, I’ll look into dust as it is more suited to ly needs. I’ll prepare
an issue for the point of cyclical dependency


Le mer. 16 juin 2021 à 22:53, Rich FitzJohn ***@***.***> a
écrit :
