### ISSUE TITLE
Function in generator to get information about user variables

### ISSUE THREAD

**Issue by OJWatson** [mrc-ide/odin#91]
Should return a named integer vector with the number of dimensions

**Comment by richfitz** [comment]
I think @jackolney needs this for baldr too

**Comment by jackolney** [comment]
Yes! [baldr](https://github.com/jackolney/baldr) needs to a vector of user variables to generate a list of checkboxes for sliders etc.

**Comment by richfitz** [comment]
See also #93 - if that's going to happen this should return a data.frame because that's more extensible.  So we'd return (in the first instance) name / dimensions, and then from a model (rather than a generator) return values too, then once #93 is done, return min/max

**Comment by richfitz** [comment]
Generalises #65

**Comment by richfitz** [comment]
The trick here is that the generator is simply a function.  The simplest approach might be to use a generic (`summary` perhaps?) to hide the details of how this works?

**Comment by richfitz** [comment]
Going with `coef` here and doing some bits to make that hopefully a bit more obvious.  Will be added to the generated model too

**Comment by richfitz** [comment]
This is done!  `coef()` on a generator function will give you back a little data.frame of user variable information.  I can grow that if more is needed @jackolney (e.g., to support bounds on variables)
